services:
  valkey-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        valkey_version: '7.2.6'
        platform: 'linux/amd64'
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
