services:
  valkey-cluster:
    environment:
      IP: ${VALKEY_CLUSTER_IP:-}
      STANDALONE: ${VALKEY_USE_STANDALONE:-}
    build:
      context: .
      args:
        VALKEY_VERSION: ${VALKEY_VERSION:-8}
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
